Feat/refactoring for reviewer
phucnh22/ph-learn-to-code pull request #3
Opened 2023-04-12 09:00 UTC by phucnh22

empty branch for code review

2023-04-13 08:05 UTC, danizao commented on life_expectancy/cleaning.py
> +    ).join(df_unpivot[[value_name, 'value']])
- maybe this ".join" should be aligned with the ".rename" for better understanding?
- maybe the ")" should be in the upper line
- maybe not....i just realized that the join is not included in the ()
- Anyway the alignment of the code was not clear to me, maybe we should discuss it in the class

2023-04-13 08:10 UTC, danizao reviewed
Phuc, I did not find a clear comment to make, just on the unpivot_data method but not sure how to solve it, just didn't look well aligned for the reader. Also 109 lines of code looks too much for me. I have spent 30 minutes "trying" to find more comments  but  I cannot look into it anymore, sorry.
Well done anyway, looks much more clear than mine :-)

2023-04-13 15:01 UTC, MrCordeiro requested changes

2023-04-23 06:49 UTC, phucnh22 commented
Finished

2023-04-23 06:49 UTC, closed without merging